package com.pictureair.photopass.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pictureair.photopass.entity.PhotoInfo;

import com.pictureair.photopass.greendao.PhotoInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig photoInfoDaoConfig;

    private final PhotoInfoDao photoInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        photoInfoDaoConfig = daoConfigMap.get(PhotoInfoDao.class).clone();
        photoInfoDaoConfig.initIdentityScope(type);

        photoInfoDao = new PhotoInfoDao(photoInfoDaoConfig, this);

        registerDao(PhotoInfo.class, photoInfoDao);
    }
    
    public void clear() {
        photoInfoDaoConfig.clearIdentityScope();
    }

    public PhotoInfoDao getPhotoInfoDao() {
        return photoInfoDao;
    }

}
