package com.pictureair.photopass.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.pictureair.photopass.entity.PhotoInfo2;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PHOTO_INFO2".
*/
public class PhotoInfo2Dao extends AbstractDao<PhotoInfo2, Long> {

    public static final String TABLENAME = "PHOTO_INFO2";

    /**
     * Properties of entity PhotoInfo2.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PhotoId = new Property(1, String.class, "photoId", false, "PHOTO_ID");
        public final static Property PhotoPathOrURL = new Property(2, String.class, "photoPathOrURL", false, "PHOTO_PATH_OR_URL");
    }


    public PhotoInfo2Dao(DaoConfig config) {
        super(config);
    }
    
    public PhotoInfo2Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PHOTO_INFO2\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PHOTO_ID\" TEXT," + // 1: photoId
                "\"PHOTO_PATH_OR_URL\" TEXT);"); // 2: photoPathOrURL
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PHOTO_INFO2\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PhotoInfo2 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String photoId = entity.getPhotoId();
        if (photoId != null) {
            stmt.bindString(2, photoId);
        }
 
        String photoPathOrURL = entity.getPhotoPathOrURL();
        if (photoPathOrURL != null) {
            stmt.bindString(3, photoPathOrURL);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PhotoInfo2 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String photoId = entity.getPhotoId();
        if (photoId != null) {
            stmt.bindString(2, photoId);
        }
 
        String photoPathOrURL = entity.getPhotoPathOrURL();
        if (photoPathOrURL != null) {
            stmt.bindString(3, photoPathOrURL);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PhotoInfo2 readEntity(Cursor cursor, int offset) {
        PhotoInfo2 entity = new PhotoInfo2( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // photoId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // photoPathOrURL
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PhotoInfo2 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPhotoId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPhotoPathOrURL(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PhotoInfo2 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PhotoInfo2 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PhotoInfo2 entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
