package com.pictureair.photopassCopy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.pictureair.photopassCopy.entity.ADLocationInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ADLOCATION_INFO".
*/
public class ADLocationInfoDao extends AbstractDao<ADLocationInfo, Long> {

    public static final String TABLENAME = "ADLOCATION_INFO";

    /**
     * Properties of entity ADLocationInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LocationId = new Property(1, String.class, "locationId", false, "LOCATION_ID");
        public final static Property DescriptionCH = new Property(2, String.class, "descriptionCH", false, "DESCRIPTION_CH");
        public final static Property DescriptionEN = new Property(3, String.class, "descriptionEN", false, "DESCRIPTION_EN");
    }


    public ADLocationInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ADLocationInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ADLOCATION_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LOCATION_ID\" TEXT," + // 1: locationId
                "\"DESCRIPTION_CH\" TEXT," + // 2: descriptionCH
                "\"DESCRIPTION_EN\" TEXT);"); // 3: descriptionEN
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ADLOCATION_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ADLocationInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String locationId = entity.getLocationId();
        if (locationId != null) {
            stmt.bindString(2, locationId);
        }
 
        String descriptionCH = entity.getDescriptionCH();
        if (descriptionCH != null) {
            stmt.bindString(3, descriptionCH);
        }
 
        String descriptionEN = entity.getDescriptionEN();
        if (descriptionEN != null) {
            stmt.bindString(4, descriptionEN);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ADLocationInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String locationId = entity.getLocationId();
        if (locationId != null) {
            stmt.bindString(2, locationId);
        }
 
        String descriptionCH = entity.getDescriptionCH();
        if (descriptionCH != null) {
            stmt.bindString(3, descriptionCH);
        }
 
        String descriptionEN = entity.getDescriptionEN();
        if (descriptionEN != null) {
            stmt.bindString(4, descriptionEN);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ADLocationInfo readEntity(Cursor cursor, int offset) {
        ADLocationInfo entity = new ADLocationInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // locationId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // descriptionCH
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // descriptionEN
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ADLocationInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLocationId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescriptionCH(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDescriptionEN(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ADLocationInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ADLocationInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ADLocationInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
